name: robot_calendar
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  table_calendar: ^3.0.9
  shared_preferences: ^2.0.6
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/robot1.png
    - assets/box_background.png
    - assets/check.png
    - assets/cross.png

